import type { NextPage } from 'next'
import Head from 'next/head'
import { PrimaryButton } from '../components/StyledComponents/PrimaryButton'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />         
      </Head>

      
      <div className='h-screen w-full flex flex-col justify-center items-center'>
        <h1 className='text-h1 text-textColor font-semibold uppercase'>welcome to rectvision</h1>
        <br />
        <div className='w-52 flex'>
          <PrimaryButton $fullWidth={true} $as = 'a' href="/auth/signup" >
            <span>sign up</span>
          </PrimaryButton>
        </div>
        <p className='text-h3 font-bold'>or</p>
        <div className='w-52 flex'>
          <PrimaryButton $fullWidth={true} $as = 'a' href="/auth/signin" >
            <span>sign in</span>
          </PrimaryButton>
        </div>
    </div>
      
    </div>
  )
}

export default Home
